from .exceptions import ErrorResult

__all__ = ("ErrorResult",)
